"""The `edge_test` folder: what travels to the device, and that the device test can actually fail.

No AWS, no built dataset, no GPU. The folder is assembled here from a synthetic window and random
weights, because what is under test is its contract - the modules it may import, the numerics it
has to reproduce, which windows get packed - and not any particular checkpoint.
"""

from __future__ import annotations

import ast
import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from edge_test import run_inference as runner
from models.unet1d import UNet1D
from phase.decode import decode, transition_matrix
from phase.labels import N_CLASSES
from phase.preprocess import WINDOW, normalise_window
from tests import synthetic

REPO_ROOT = Path(__file__).resolve().parent.parent
FOLDER = REPO_ROOT / "edge_test"

TRACKED = ("__init__.py", "run_inference.py", "pack.py", "report.py", "README.md")
"""The folder's own files. Everything else in it is generated by `pack.py`, which is the point:
there is exactly one copy of the device code and it is not in a build directory."""

INFERENCE = ("run_inference.py", *runner.NUMERIC_MODULES)
"""The inference path. numpy and torch, nothing else - this is the part that has to run even where
matplotlib does not."""

PLOTTING = ("report.py", *runner.PLOT_MODULES)
"""The drawing path, which also runs on the device. matplotlib and pandas are allowed here because
`holosissystem` installs both; the run's data is written before any of it is imported, so a device
without them still produces a complete run."""

BANNED = ("pytorch_lightning", "lightning", "hydra", "omegaconf", "clearml", "boto3",
          "sqlalchemy", "pymysql", "sklearn", "holosissystem", "holosis_aws_manager")
"""Not on a device at all, for either path. `phase/dataset.py` is the near miss: four lines of
numpy and a pandas frame, and it reaches the database layer through `phase.building`."""

HEAVY = ("pandas", "matplotlib")
"""Fine for the figures, fatal for the inference."""


FIRST_PARTY = ("phase", "models", "edge_test")

MODEL = {"in_channels": 1, "channels": [8, 12], "bottleneck": 16, "kernel_size": 5,
         "dropout": 0.0}
DECODING = {"viterbi": True, "switch_penalty": 2.0, "enforce_min": False,
            "min_duration": {"unknown": 1, "inhale": 3, "exhale": 3, "stop": 2},
            "allowed": {"unknown": ["inhale", "exhale", "stop"], "inhale": ["unknown"],
                        "exhale": ["unknown", "stop"], "stop": ["unknown", "inhale"]}}


def _imports(path: Path):
    """Every import in a module, at any indentation, as (root package, full module)."""
    for node in ast.walk(ast.parse(path.read_text())):
        if isinstance(node, ast.Import):
            for alias in node.names:
                yield alias.name.split(".")[0], alias.name
        elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
            yield node.module.split(".")[0], node.module


# ------------------------------------------------------------------------------- the contract

def test_the_folder_holds_only_its_own_scripts_and_what_pack_generates():
    """A second copy of the device code is the thing this layout exists to prevent."""
    tracked = {path.name for path in FOLDER.iterdir()
               if path.is_file() and path.suffix in (".py", ".md")}
    assert tracked == set(TRACKED), f"unexpected tracked files: {tracked ^ set(TRACKED)}"


def test_every_module_the_device_needs_is_present():
    missing = [name for name in runner.MODULES if not (REPO_ROOT / name).exists()]
    assert not missing, f"MODULES names files that do not exist: {missing}"


def _path(name: str) -> Path:
    """A script lives in the folder; a copied module lives at its place in the repo."""
    return FOLDER / name if "/" not in name else REPO_ROOT / name


def test_nothing_that_runs_on_a_device_reaches_for_something_it_lacks():
    offenders = [f"{name} imports {module}"
                 for name in (*INFERENCE, *PLOTTING)
                 for root, module in _imports(_path(name)) if root in BANNED]
    assert not offenders, "\n".join(offenders)


def test_the_inference_path_stays_free_of_pandas_and_matplotlib():
    """A device without them must still produce a complete run - the figures are the extra."""
    offenders = [f"{name} imports {module}"
                 for name in INFERENCE
                 for root, module in _imports(_path(name)) if root in HEAVY]
    assert not offenders, "\n".join(offenders)


def test_every_first_party_import_of_the_device_code_also_travels():
    """Otherwise the folder imports a module that is not in it, and only fails on the device."""
    bundled = {name.replace("/", ".").removesuffix(".py").removesuffix(".__init__")
               for name in runner.MODULES}
    # The scripts sit beside each other in the folder and import each other by bare name there;
    # in a checkout they are `edge_test.<name>`, which is why both spellings are tried.
    bundled |= {"edge_test", "run_inference", "report"}
    escapes = [f"{name} imports {module}, which is not in MODULES"
               for name in (*INFERENCE, *PLOTTING)
               for root, module in _imports(_path(name))
               if root in FIRST_PARTY and module not in bundled]
    assert not escapes, "\n".join(escapes)


# --------------------------------------------------------------------------------- the runner

def _folder(tmp_path: Path, samples: int = 200, n: int = 3) -> Path:
    """A folder with random weights and its own answer recorded - what `pack.py` would write."""
    folder = tmp_path / "edge_test"
    (folder / runner.WAVEFORMS_DIR).mkdir(parents=True)
    torch.manual_seed(0)
    net = UNet1D(n_classes=N_CLASSES, **MODEL).eval()
    cost = transition_matrix(DECODING["allowed"], DECODING["switch_penalty"])
    rng = np.random.default_rng(0)

    for index in range(n):
        values, targets = synthetic.window(samples, rate_bpm=14.0, fps=10.0, rng=rng)
        with torch.no_grad():
            logits = net(torch.from_numpy(
                normalise_window(values)[None, None, :]))[0].permute(1, 0).numpy()
        np.savez_compressed(
            folder / runner.WAVEFORMS_DIR / runner.WAVEFORM_TEMPLATE.format(
                env=synthetic.ENV, window_id=index),
            values=values.astype(np.float32), targets=targets.astype(np.int8),
            host_logits=logits.astype(np.float32),
            host_prediction=decode(logits, cost, None).astype(np.int8),
            window_id=np.int64(index), patient=np.str_("synth-000"),
            env=np.str_(synthetic.ENV), fps=np.float32(10.0))

    torch.save({"state_dict": net.state_dict(), "model": MODEL}, folder / runner.WEIGHTS)
    (folder / runner.MANIFEST).write_text(json.dumps({
        "created": "test", "checkpoint": "none", "dataset": "synthetic", "fold": 0,
        "split": "test", "label_source": "algorithm", "normalise": WINDOW, "fps": 10.0,
        "n_windows": n, "model": MODEL, "decoding": DECODING,
        "logit_tolerance": runner.LOGIT_TOLERANCE,
        "host": {"python": "3.12.0", "torch": torch.__version__, "numpy": np.__version__,
                 "machine": "test", "platform": "test"},
        "host_macro_f1": 0.0, "mean_samples": float(samples)}))
    return folder


def _run(folder: Path, monkeypatch, runs: int = 2) -> int:
    monkeypatch.setattr(sys, "argv",
                        ["run_inference", "--folder", str(folder), "--runs", str(runs),
                         "--warmup", "0"])
    return runner.main()


def test_results_land_in_the_folders_own_out_directory(tmp_path, monkeypatch):
    """On the device as much as here. A run whose output is somewhere else is a run nobody finds."""
    folder = _folder(tmp_path)
    assert _run(folder, monkeypatch) == 0
    out = folder / runner.OUT_DIR
    assert all((out / name).exists() for name in runner.RETURN_FILES)
    # And nothing is left loose in the folder root beside the payload.
    assert not [name for name in runner.ARTIFACTS if (folder / name).exists()]


def test_the_manifest_travels_with_the_run(tmp_path, monkeypatch):
    """So a returned run names its own checkpoint, and re-packing cannot relabel it."""
    folder = _folder(tmp_path)
    assert _run(folder, monkeypatch) == 0
    packed = json.loads((folder / runner.MANIFEST).read_text())
    returned = json.loads((folder / runner.OUT_DIR / runner.MANIFEST).read_text())
    assert packed == returned


def test_the_runner_reproduces_the_recorded_answer(tmp_path, monkeypatch):
    folder = _folder(tmp_path)
    assert _run(folder, monkeypatch) == 0
    results = json.loads((folder / runner.OUT_DIR / runner.RESULTS).read_text())
    assert results["passed"]
    assert results["max_logit_drift"] == 0.0
    assert not results["mismatched_windows"]
    assert len(results["windows"]) == 3


def test_every_run_is_measured_not_just_the_first(tmp_path, monkeypatch):
    """The latency distribution is the artifact, so the rows have to be there to build one."""
    folder = _folder(tmp_path)
    assert _run(folder, monkeypatch, runs=4) == 0
    rows = (folder / runner.OUT_DIR / runner.TIMINGS).read_text().strip().splitlines()
    assert len(rows) == 1 + 3 * 4                       # header + windows x runs
    assert (folder / runner.OUT_DIR / runner.PREDICTIONS).exists()


def test_a_tampered_answer_fails(tmp_path, monkeypatch):
    """The point of the recorded logits. If this passes, the device run proves nothing."""
    folder = _folder(tmp_path)
    path = next((folder / runner.WAVEFORMS_DIR).glob("*.npz"))
    with np.load(path, allow_pickle=False) as stored:
        arrays = {key: stored[key] for key in stored.files}
    arrays["host_logits"] = arrays["host_logits"] + 1.0
    np.savez_compressed(path, **arrays)

    assert _run(folder, monkeypatch) == 1
    results = json.loads((folder / runner.OUT_DIR / runner.RESULTS).read_text())
    assert not results["passed"]
    assert results["max_logit_drift"] > runner.LOGIT_TOLERANCE


def test_the_run_draws_its_own_figures_into_its_own_subfolder(tmp_path, monkeypatch):
    """The plot is the artifact somebody looks at, so it is made where the run happened."""
    folder = _folder(tmp_path)
    assert _run(folder, monkeypatch) == 0
    results = json.loads((folder / runner.OUT_DIR / runner.RESULTS).read_text())
    drawn = folder / runner.OUT_DIR / "report" / results["finished"]
    assert (drawn / "latency.png").exists()
    assert (drawn / "latency_summary.csv").exists()
    assert list(drawn.glob("predictions_page_*.png"))
    # And the run it describes is copied in beside the figures.
    assert all((drawn / name).exists() for name in runner.RETURN_FILES)
    assert (folder / runner.OUT_DIR / "report" / "index.csv").exists()


def test_no_figures_still_writes_a_complete_run(tmp_path, monkeypatch):
    """A device without matplotlib has to end up with data that can be drawn anywhere else."""
    folder = _folder(tmp_path)
    monkeypatch.setattr(sys, "argv", ["run_inference", "--folder", str(folder), "--runs", "1",
                                      "--warmup", "0", "--no-figures"])
    assert runner.main() == 0
    assert all((folder / runner.OUT_DIR / name).exists() for name in runner.RETURN_FILES)
    assert not (folder / runner.OUT_DIR / "report").exists()


def test_an_empty_folder_is_reported_rather_than_passing(tmp_path, monkeypatch):
    folder = _folder(tmp_path)
    for path in (folder / runner.WAVEFORMS_DIR).glob("*.npz"):
        path.unlink()
    assert _run(folder, monkeypatch) == 2


def test_the_weights_load_without_unpickling_anything(tmp_path):
    """`weights_only=True` is what makes it safe to run a file that arrived over scp."""
    folder = _folder(tmp_path)
    stored = torch.load(folder / runner.WEIGHTS, map_location="cpu", weights_only=True)
    assert set(stored) == {"state_dict", "model"}
    assert all(isinstance(value, torch.Tensor) for value in stored["state_dict"].values())


# ---------------------------------------------------------------------------- what gets packed

def test_only_windows_of_the_asked_for_duration_are_packed():
    """A latency spread over mixed lengths measures the lengths - the net is convolutional."""
    from edge_test.pack import one_length

    frame = pd.DataFrame([{"samples": 200, "analysis_fps": 10.0, "n_unknown": 10},
                          {"samples": 250, "analysis_fps": 10.0, "n_unknown": 10},
                          {"samples": 400, "analysis_fps": 20.0, "n_unknown": 10}])
    # 200 at 10 fps and 400 at 20 fps are both 20 s; 250 at 10 fps is 25 s and goes.
    assert sorted(one_length(frame, 20.0)["samples"]) == [200, 400]
    assert len(one_length(frame, 0)) == 3


def test_a_window_with_no_phase_at_all_is_left_out():
    """It scores 1.00 or near zero on the one class in play and shows nothing."""
    from edge_test.pack import labelled_only

    frame = pd.DataFrame([{"samples": 200, "n_unknown": 200},
                          {"samples": 200, "n_unknown": 199},
                          {"samples": 200, "n_unknown": 0}])
    assert sorted(labelled_only(frame)["n_unknown"]) == [0, 199]


# -------------------------------------------------------------------------- normalisation

def test_normalise_window_is_a_per_window_z_score():
    out = normalise_window(np.array([1.0, 2.0, 3.0, 4.0], dtype=np.float32))
    assert out.dtype == np.float32
    assert abs(float(out.mean())) < 1e-6
    assert abs(float(out.std()) - 1.0) < 1e-6


def test_a_flat_window_keeps_its_scale():
    """Dividing an apnoea by its own noise would turn that noise into breathing."""
    assert np.allclose(normalise_window(np.full(50, 7.0, dtype=np.float32)), 0.0)


def test_any_other_mode_is_a_pass_through():
    values = np.array([1.0, 5.0, 9.0], dtype=np.float32)
    assert np.allclose(normalise_window(values, "none"), values)
